### ISSUE TITLE
Fixing HAVE_UX_FLOW compilation issue

### ISSUE THREAD

**Issue by drvarun** [archethic-foundation/archethic-ledger#15]
The default Makefile contains the default configuration for compiling Bolos app.
However, 
`DEFINES += HAVE_UX_FLOW`
causes issues during compilation, namely related to graphics element defined in the main.c of the Archethic Ledger App.
To be debugged

**Comment by prix-uniris** [comment]
This is due to following reason:
1. When we add HAVE_UX_FLOW, it makes HAVE_UX_LEGACY disable which defined structs such as ux_menu_entry_s, ux_menu_entry_t, etc. for more reference please look ifdef HAVE_UX_LEGACY inside ux.h which is at path /lib_ux/ux.h.
2. According to docs we should make use of macros UX_FLOW and predefined macros to defined transaction flow and further flow. To define multi step transaction flow recommended way is: https://developers.ledger.com/docs/nano-app/advanced-display-management/
